import type { Metadata } from "next";
import { Lato } from "next/font/google";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { AuthorsProvider } from "@/modules/authors/context/AuthorsContext";

const geistSans = Lato({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

const geistMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "PreParcial",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const linkStyle: React.CSSProperties = {
    padding: "6px 10px",
    border: "1px solid #ddd",
    borderRadius: 8,
    textDecoration: "none",
  };
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthorsProvider>
        <div style={{maxWidth: 920, margin: "0 auto", padding: 16}}>
          <header
            style={{
              display: "flex",
              gap: 8,
              alignItems: "center",
              marginBottom: 16,
            }}
          >
            <h1 style={{ fontSize: 18, margin: 0, marginRight: 8}}>
              PreParcial
            </h1>
            <nav style={{ display: "flex", gap:8}}>
              <Link href="/" style={linkStyle}>
              Inicio
              </Link>
              <Link href="/authors" style={linkStyle}>
              Autores
              </Link>
              <Link href="/crear" style={linkStyle}>
              Crear autor
              </Link>
            </nav>
          </header>
          {children}
        </div>
        </AuthorsProvider>
      </body>
    </html>
  );
}
